### ISSUE TITLE
Why did you delete my issue?

### ISSUE THREAD

**Issue by sbyeniden** [OoLunar/Music_Player#9]
You fucking coward retard nigger jew TCD veteran. What the fuck are you scared of? Job availability? Well incase your forgetful TCD veteran universe brain forgot it, I repeat it again, *being a TCD veteran **DOES NOT** give you a job*.

You think I'm so chutiya that I didn't make [a webarchive](https://web.archive.org/web/20201008072243/https://github.com/OoLunar/Music_Player/issues/5), well guess what, I did it before you fucking delete this issue (as expected from a faggot TCD veteran), now it's a proof of your arrogance and negligence.

**Take this a rule:** NEVER, EVER, try to prove yeniden wrong. Yeniden will prove you wrong.
NOW IF YOU STILL THINK YOU'RE RIGHT PLEASE PLEASE PLEASE KILL YOURSELF.

**Comment by OoLunar** [comment]
First off, I never deleted the issue. I locked it. 

Second off, quit harassing me. We all have better things to do.

**Comment by sbyeniden** [comment]
Oops, sorry bro.

**Comment by OoLunar** [comment]
See https://github.com/OoLunar/Hideki/tree/concept for how the music player will be remade.
